curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%201.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%202.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%203.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%204.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%205.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%206.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%207.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%208.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%209.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2010.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2011.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2012.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2013.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2014.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2015.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2016.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2017.sce -O
curl https://raw.githubusercontent.com/KGowthamTN/ITWorkshop/main/EX%2018.sce -O